name: Clang Conan

on:
  push:
    paths-ignore:
    - 'scripts/**'
    - 'README.md'

env:
  CONAN_UPLOAD: "https://api.bintray.com/conan/sintef-ocean/conan"
  CONAN_PASSWORD_SINTEF: ${{ secrets.BINTRAY_API_KEY }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.BINTRAY_USER }}
  CONAN_NON_INTERACTIVE: True
  CONAN_USE_ALWAYS_SHORT_PATHS: True
  SINTEF_PKG: qt/5.15.0
  SINTEF_CHANNEL: bincrafters/stable
  SINTEF_OPTS: -o qt:qtsvg=True

jobs:
  conan-with-clang:
    name: Conan
    runs-on: ${{ matrix.os }}
    env:
      CC: clang-${{ matrix.compiler_version }}
      CXX: clang++-${{ matrix.compiler_version }}
    strategy:
      fail-fast: false
      matrix:
        compiler_version: [8, 9, 10]
        build_type: [Debug, Release]
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo pip3 install --upgrade setuptools pip
          sudo pip3 install conan requests
          sudo pip3 install conan_package_tools
          sudo apt-get install clang-tools-10
      - name: Configure Conan
        run: |
          conan remote add sintef ${CONAN_UPLOAD} --insert 0
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      - name: Conan create
        run: |
          conan install ${SINTEF_PKG}@${SINTEF_CHANNEL} \
            -s build_type=${{ matrix.build_type }} \
            -s compiler.version=${{ matrix.compiler_version }} \
            -s compiler.libcxx=libstdc++11 \
            -b missing -b outdated ${SINTEF_OPTS}
      - name: Conan upload
        run: |
          conan upload --all -c -r sintef ${SINTEF_PKG} --retry 10 --retry-wait 20
