name: GCC Conan

on:
  push:
    paths-ignore:
    - 'scripts/**'
    - 'README.md'

env:
  CONAN_UPLOAD: "https://api.bintray.com/conan/sintef-ocean/conan"
  CONAN_PASSWORD_SINTEF: ${{ secrets.BINTRAY_API_KEY }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.BINTRAY_USER }}
  CONAN_NON_INTERACTIVE: True
  CONAN_USE_ALWAYS_SHORT_PATHS: True
  SINTEF_PKG: yaml-cpp/0.6.3
  SINTEF_CHANNEL:
  # "bincrafters/stable"
  # qt/5.15.0@bincrafters/stable
  SINTEF_OPTS:
  # -o qt:qtsvg=True

jobs:
  conan-with-gcc:
    name: Conan
    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-${{ matrix.compiler_version }}
      CXX: g++-${{ matrix.compiler_version }}
    strategy:
      fail-fast: false
      matrix:
        compiler_version: [6, 7, 8, 9]
        build_type: [Debug, Release]
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        exclude:
          - os: ubuntu-16.04
            compiler_version: 7
          - os: ubuntu-16.04
            compiler_version: 8
          - os: ubuntu-16.04
            compiler_version: 9
          - os: ubuntu-18.04
            compiler_version: 6
          - os: ubuntu-18.04
            compiler_version: 9
          - os: ubuntu-20.04
            compiler_version: 6
          - os: ubuntu-20.04
            compiler_version: 7
          - os: ubuntu-20.04
            compiler_version: 8
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo pip3 install --upgrade setuptools pip
          sudo pip3 install conan requests
          sudo pip3 install conan_package_tools
          if [ ${{ matrix.compiler_version }} -eq 6 ]; then
              sudo add-apt-repository ppa:ubuntu-toolchain-r/test
              sudo apt-get update
              sudo apt-get install gcc-6 g++-6 -y
          fi
      - name: Configure Conan
        run: |
          conan remote add sintef ${CONAN_UPLOAD} --insert 0
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      - name: Conan install
        run: |
          conan install ${SINTEF_PKG}@${SINTEF_CHANNEL} \
            -s build_type=${{ matrix.build_type }} \
            -s compiler.version=${{ matrix.compiler_version }} \
            -s compiler.libcxx=libstdc++11 \
            --build missing -b outdated ${SINTEF_OPTS}
      - name: Conan upload
        run: |
          conan upload --all -c -r sintef ${SINTEF_PKG} --retry 10 --retry-wait 20
